# Generated by Django 5.2.7 on 2025-10-28 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myz_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/', verbose_name='Файл книги'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст книги'),
        ),
    ]
