# Generated by Django 5.2.8 on 2025-11-13 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myz_app', '0002_book_book_file_book_book_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_text',
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter_number', models.PositiveIntegerField(verbose_name='Номер главы')),
                ('title', models.CharField(max_length=200, verbose_name='Название главы')),
                ('content', models.TextField(verbose_name='Текст главы')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='myz_app.book')),
            ],
            options={
                'ordering': ['chapter_number'],
                'unique_together': {('book', 'chapter_number')},
            },
        ),
    ]
